eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://user1:pass123@localhost:8761/eureka/
server:
  port: 8084
spring:
  application:
    name: item-services
  boot:
    admin:
      client:
        url: http://admin:admin@localhost:9090/
  datasource:
    url: jdbc:h2:mem:itemDB
    password: sa
    username: sa
  security:
    user:
      name: user1
      password: pass1234
  h2:
    console:
      enable: true
      settings:
        web-allow-others: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'