eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8761
spring:
  application:
    name: discovery-project1
  security:
    user:
      name: user1
      password: pass123
  boot:
    admin:
      client:
        url: http://admin:admin@localhost:9090/
  
